BrainPad/cliboa

- Pipfile
- cliboa/core/strategy.py
Serialize step class by cloudpickle, instead of python default.
> Bug fix: multiprocessing does not work

- .github/workflows/test.yaml
add python3.8 and 3.9 to GitHubActions
* test.yamlの内容
* ciの実行結果
Confirmed
GitHubActionsで実行済み
> [8/13〆] add python3.8 and 3.9 to GitHubActions

- cliboa/core/manager.py
- cliboa/core/validator.py
- cliboa/test/core/test_manager.py
> make unavailable "injection"

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_column_concat.md
Make CsvColumnConcat class
Supports concat with 3 or more lines.
* CsvColumnConcat class behavior
* Is there any discomfort?
Confirmed
Add unittest is passed.
Existing unittest is passed.
* Mid-August 2021
> Make CsvColumnConcat class

- cliboa/test/scenario/transform/test_csv.py
- cliboa/test/scenario/transform/test_file.py
- cliboa/test/util/test_csv.py
- cliboa/util/csv.py
https://github.com/BrainPad/cliboa/issues/230
Confirmed
> [FIX] CsvColumnExtract erase all csv columns

- cliboa/conf/__init__.py
- cliboa/template/bin/clibomanager.py
LISBOA -> CLIBOA
Confirmed
Anytime
> Rename to cliboa

- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_convert.md
Add no header option for CsvConvert class
* CsvConvert content
* csv_convert.md's content
Confirmed
* ASAP
> Add no header option for CsvConvert class

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_column_hash.md
- docs/modules/hash_convert.md
Make CsvColumnHash class
Support hash designated columns with SHA256
* 1 CsvColumnHash class behavior
* 2 
Confirmed
Add pytest is passed.
> Make CsvColumnHash class

- cliboa/core/worker.py
- cliboa/scenario/extract/sqlite.py
- cliboa/scenario/load/gcp.py
- cliboa/scenario/load/sqlite.py
- cliboa/scenario/validator.py
- cliboa/test/scenario/test_validator.py
- cliboa/test/util/test_cache.py
- cliboa/util/cache.py
- cliboa/util/ftp_util.py
- cliboa/util/http.py
Fix mangling __ to _ , according to Google style guide.
* Fixed codes
Confirmed
ユニットテストを通しただけです。
> [〆9/15] fix mangling

- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_column_select.md
Add CsvColumnSelect class
Select columns in Csv file in specified order
* CsvColumnSelect class behavior
* Is there any discomfort?
Confirmed 
* `Not in hurry`
> Add CsvColumnSelect class

- cliboa/core/manager.py
- cliboa/test/core/test_manager.py
scenario.ymlで環境変数を利用できるようにしました。
> allow to use environment values in scenario.yml

- .github/workflows/deploy.yaml
Mask user and password.
deploy.yamlの実行結果でマスクされていることを確認してください。
Confirming
> add masking

- cliboa/adapter/mysql.py
- cliboa/adapter/postgres.py
- cliboa/adapter/rdbms.py
- cliboa/scenario/__init__.py
- cliboa/scenario/extract/postgres.py
- cliboa/scenario/load/mysql.py
- cliboa/scenario/load/postgres.py
- cliboa/scenario/rdbms.py
- cliboa/template/Pipfile.above36
- cliboa/template/Pipfile.above37
- cliboa/template/Pipfile.above38
- cliboa/template/Pipfile.above39
- cliboa/util/rdbms_util.py
- docs/modules/mysql_write.md
- docs/modules/postgresql_read.md
- docs/modules/postgresql_write.md
Add PostgreAqlAdaptor (PostgreSqlRead, PostgreSqlWrite)
Also added mySqlWrite class.
> postgre sql adaptor

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_value_extract.md
Add the function to extract the character string from the CSV column.
Confirmed
> Add the function to extract the character string from the CSV column.

- cliboa/scenario/transform/file.py
- cliboa/test/scenario/transform/test_file.py
- docs/modules/file_rename.md
Supports string substitution in FileRename class
Confirmed
> Supports string substitution in FileRename class

- cliboa/scenario/__init__.py
- cliboa/scenario/extract/sftp.py
- cliboa/test/scenario/extract/test_sftp.py
- cliboa/util/sftp.py
- docs/modules/sftp_file_check.md
SFTP上のファイル存在チェックのみ行うクラスを追加しました。
存在チェックのみ行うポーリングのような使い方を想定してます。
違和感ないか
実施済み。
2/25(金)目処、お手隙の際に
ご確認お願いします。
> 333 Added SFTP File Check function

- cliboa/scenario/transform/csv.py
- cliboa/scenario/transform/json.py
Additional support to continue processing even if some files fail.
Confirmed
> Additional support to continue processing even if some files fail.

- cliboa/scenario/load/aws.py
Allow uploading directly under the bucket with S3Upload
Confirmed
* `As soon as possible`
> Allow uploading directly under the bucket with S3Upload

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/json.py
- cliboa/test/scenario/transform/test_json.py
- docs/modules/jsonl_add_key_value.md
Add key value pairs to Jsonl files
Confirmed
* `At the timing of your hand.`
> Add key value pairs to Jsonl files

- cliboa/scenario/__init__.py
- cliboa/scenario/extract/aws.py
- docs/modules/s3_download_file_delete.md
Added S3 download file delete function
Confirmed
This function doesn't work by itself, executed with S3Download [Development-Environment](https://github.com/BrainPad/cliboa/wiki/Development-Environment) and confirmed that only the downloaded file was deleted.
> Added S3 download file delete function

- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_column_extract.md
Extend CsvColumnExtract to support column deletion
Confirmed
> Extend CsvColumnExtract to support column deletion

- .github/workflows/test.yaml
Make pipenv install successful
* whether the CI is successful
Not necessary
Only confirm that CI succeeds
> Make pipenv install successful

- cliboa/scenario/transform/file.py
- cliboa/test/scenario/transform/test_file.py
- docs/modules/file_rename.md
#370 の機能修正
* FileRenameシナリオを既に使っているプロジェクトに影響が出なさそうか？
* cliboaへのPRが初めてなので、規約違反などがないか？
Confirmed
- ローカル環境での確認（↓のシナリオで期待通りの動作をしたことを確認した）
```
scenario:
- step: Rename file (deletion of character)
class: FileRename
arguments:
src_dir: /root
src_pattern: foo_delete\.txt
regex_pattern: _delete
rep_str: ""
Input: /root/foo_delete.txt
Output: /root/foo.csv
```
* いつでも
> [modified] empty character

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_column_copy.md
csvの指定されたカラムデータを指定されたカラムにコピーする（既に存在していたら上書き更新）
#386 
* 他の処理クラスのオプションとして、機能を付け加えて実装したほうが良いか？（処理自体がシンプルなので）
* テストの網羅性（正常系しか書いていません）
* [追記] パラメータがない場合のテストを入れました
* ドキュメントを新規作成したので、抜け漏れがないか？
Confirmed
- ローカルで実行した
* なるはや（1週間以内にマージ）
> [add] csv column copy

- cliboa/scenario/transform/aes.py
- cliboa/test/scenario/transform/test_aes.py
- docs/modules/aes_decrypt.md
- docs/modules/aes_encrypt.md
Make AesEncrypt class and AesDecrypt class
Confirmed
* `When you're reddy.`
> Make AesEncrypt class and AesDecrypt class

- cliboa/scenario/transform/csv.py
cliboaの拡張を行うことを想定してprivate関数をpublic関数として再定義
* テストが落ちていないか？
Confirmed
- ローカルでテスト実行
* 今年まで
> [modify] public func

- docs/modules/gcs_upload.md
typo 修正
None
Not necessary
* いつでも
> [modify] typo bucker

- .github/workflows/test.yaml
- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/extract/test_http.py
- cliboa/test/scenario/transform/test_csv.py
処理の初めにソース元ファイルをconcatしておいてから、それぞれのファイルをcsv化する
* テストが通っているか？
* pandas.concatの処理に準拠しているか？
Confirmed
* デグレなのでなるはや
> [modify] concat仕様に合わせる

- cliboa/scenario/extract/gcp.py
Make it possible to specify the file name in src_pattern in GcsDownload
Confirmed
Confirmed by actually connecting to GCS
* `When you're reddy.`
> Make it possible to specify the file name

- cliboa/core/manager.py
- cliboa/test/core/test_manager.py
with_varsによる文字列置換処理を変更
- [仕様変更なし] argmentsにstr型が与えられた時のみ置換処理を行う
- [仕様変更なし] argmentsにdictやlistが与えられた時は、ネストしたりループ処理を行なってそれぞれの値を個別に置換
- [仕様変更] datetimeなどのstr以外の型がargmentsにある時は、置換処理を行わない
* この仕様変更で問題ないか？
* テストケースの漏れ
Confirmed
* cliboaをシステムで使っているので、なるべく早く
> Values not replaced by with_vars remain unchanged

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/file.py
- cliboa/test/scenario/transform/test_file.py
- docs/modules/file_copy.md
Create FileCopy class
Confirmed
> Create FileCopy class

- cliboa/connect/http_request.py
- cliboa/scenario/extract/http.py
- cliboa/test/connect/test_http_request.py
- cliboa/test/scenario/test_base.py
- cliboa/test/util/test_http.py
- cliboa/util/http.py
- docs/modules/http_delete.md
- docs/modules/http_download.md
- docs/modules/http_get.md
- docs/modules/http_post.md
- docs/modules/http_put.md
Cut out the GET request module from scenario and create it in connect.
Also test code is supported.
Confirmed
> Create HTTP request module

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_duplicate_row_delete.md
Create a class to remove duplicate rows
Confirmed
> Create a class to remove duplicate rows

- cliboa/scenario/__init__.py
- cliboa/scenario/extract/http.py
- cliboa/scenario/http.py
- cliboa/scenario/load/http.py
- cliboa/test/scenario/extract/test_azure.py
- cliboa/test/scenario/extract/test_http.py
- cliboa/test/scenario/load/test_http.py
- cliboa/test/util/test_http.py
- cliboa/util/http.py
Refacter HTTP request module
Confirmed
> Refacter HTTP request module

- cliboa/scenario/transform/file.py
Modify behavior when handling .bz files with FileDecompress class.
Points to Check
Is there any discomfort in the corresponding parts and contents?
Test
Confirmed
Review Limit
When you're ready.
> Modify behavior when handling .bz files with FileDecompress class

- cliboa/scenario/extract/sftp.py
Absorb the impact of integrating the SFTP utility into the adapter.
fix dead classes.
Confirmed
> Absorb the impact of integrating the SFTP utility into the adapter

- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_convert.md
Added option to specify escape character to CsvConvert class.
* 1
* 2
Confirmed
> [9/15]Specify escape character in CsvConvert class

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_row_delete.md
Compare csv files by specifying columns.
If the same element exists, delete the corresponding line.
Confirmed
> Compare csv specing clumns, same element exists, delete the corresponding line.

- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
Prevent the value from being empty in pandas read_csv
Confirmed
> Prevent the value from being empty in pandas read_csv

- cliboa/scenario/__init__.py
Enable CsvMergeExclusive class to start.
* Added to scenario/init.py
Confirmed
> Enable CsvMergeExclusive class to start.

- .github/workflows/test.yaml
- cliboa/adapter/ftp.py
- cliboa/adapter/sftp.py
- cliboa/core/manager.py
- cliboa/scenario/transform/file.py
- cliboa/template/pyproject.above310.toml
- cliboa/template/pyproject.above37.toml
- cliboa/template/pyproject.above38.toml
- cliboa/template/pyproject.above39.toml
- cliboa/test/scenario/transform/test_file.py
Banditによるpythonコードの脆弱性テストを追加
Banditのseverityはhighに指定
脆弱性テストにヒットしたsshライブラリ、ftpライブラリなどは一旦#necコメントを追記して脆弱性チェックへのヒットを回避する形にしています
Python3.7はbanditの最新版が動かないのでテスト対象から除外
* GitHubActionsのテスト内容
* banditの仕様 https://bandit.readthedocs.io/en/latest/index.html
Confirming
> [〆10/24]add the test by bandit

- .github/workflows/test.yaml
Make tests manually executable.
* 1
* 2
Confirmed / Confirming / Not necessary
> Make tests manually executable

- cliboa/scenario/transform/csv.py
Write here
* 1
* 2
Confirmed / Confirming / Not necessary
> Avoid using chunksize param in CsvMergeExclusive class.

- cliboa/core/listener.py
- cliboa/core/scenario_queue.py
- cliboa/core/step_queue.py
- cliboa/core/strategy.py
- cliboa/core/worker.py
- cliboa/interface.py
- cliboa/scenario/extract/file.py
- cliboa/scenario/load/aws.py
- cliboa/scenario/load/file.py
- cliboa/scenario/sample_step.py
- cliboa/template/bin/clibomanager.py
- cliboa/test/__init__.py
- cliboa/test/adapter/test_file.py
- cliboa/test/core/test_factory.py
- cliboa/test/core/test_listener.py
- cliboa/test/core/test_step_queue.py
- cliboa/test/core/test_strategy.py
- cliboa/test/core/test_worker.py
- cliboa/test/scenario/extract/test_file.py
- cliboa/test/scenario/extract/test_ftp.py
- cliboa/test/scenario/extract/test_sftp.py
- cliboa/test/scenario/load/test_file.py
- cliboa/test/scenario/test_validator.py
- cliboa/test/test_client.py
- cliboa/test/util/test_date.py
- cliboa/util/date.py
- cliboa/util/exception.py
- cliboa/util/parallel_with_config.py
- cliboa/util/string.py
copyrightに2019が残っていたので2019を削除
* copyrightの妥当性
Confirmed
> [〆1/19]fix copyright

- docs/default_etl_modules.md
Fixed minor error in default_etl_modules.md.
* Whether the modifications are appropriate.
Not necessary
(Documentation changes only - no functional changes that require testing)
* None
> Fix documentation issues in default_etl_modules.md

- .github/workflows/check_merged_branches.yaml
- CONTRIBUTING.md
Update about issue #483
* Please check if the CI implementation works as intended
Confirmed
> #483 Add rule to delete merged branches and set up CI check. (due 2025/09/30)

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_split.md
Implement CsvSplitRows class - issue #493 
- Please check if the CsvSplitRows class is implemented as intended
- Please check if the test cases are appropriate
Confirmed
**Pass cliboa-test-functional**
> Implement CsvSplitRows class. (fixes #493, due 2025/08/29)

- cliboa/core/listener.py
update listener class comments, add type-hints, fix arguments.
* any unforeseen impact
Confirmed
Pass **cliboa-test**
> refactor: update listener comments, type hints, and arguments.

- .github/workflows/check_merged_branches.yaml
Fixes #536 
* any unforeseen impact
Confirmed
https://github.com/BrainPad/cliboa/actions/runs/18155908741
> ci: exclude released version branch to check merged branches. (fixes #536)
