- cliboa/scenario/extract/gcp.py
- cliboa/scenario/gcp.py
- cliboa/scenario/load/gcp.py
- cliboa/util/gcp.py
- docs/modules/bigquery_file_download.md
- docs/modules/bigquery_write.md
- docs/modules/firestore_document_create.md
- docs/modules/firestore_document_download.md
- docs/modules/gcs_download.md
- docs/modules/gcs_upload.md
- tests/util/test_gcp.py
Fixed GCP modules to support service account .json file path or a dictionary containing service account info in Google format.
The following is an example of specifying a dictionary.
```
scenario:
- step:
class: GcsDownload
arguments:
project_id:
location:
credentials: {
"type": "service_account",
"project_id": "xxxxxxxxx",
...
}
bucket:
prefix:
src_pattern:
dest_dir:
```
> #77 Supports GCP module using a dictionary containing service account info in Google format.

- cliboa/cli/cliboadmin.py
```
Traceback (most recent call last):
File "/home/cliboa/.local/bin/cliboadmin", line 8, in <module>
sys.exit(main())
File "/home/cliboa/.local/lib/python3.7/site-packages/cliboa/cli/cliboadmin.py", line 181, in main
admin.main()
File "/home/cliboa/.local/lib/python3.7/site-packages/cliboa/cli/cliboadmin.py", line 42, in main
self._init_project(self._args.dir_name)
File "/home/cliboa/.local/lib/python3.7/site-packages/cliboa/cli/cliboadmin.py", line 57, in _init_project
self._create_ess_files(ini_dir)
File "/home/cliboa/.local/lib/python3.7/site-packages/cliboa/cli/cliboadmin.py", line 82, in _create_ess_files
else cliboa_install_paths[1]
IndexError: list index out of range
```
I think site.getsitepackages() only looks for global site-packages.
However, it can also be installed in the …
> cliboadmin init was failed #131

- .github/workflows/security.yaml
- cliboa/test/adapter/test_rdbms.py
- cliboa/test/util/test_sftp.py
git-secretsによる機密情報チェックをGitHubActionsのCIパイプラインに追加しました。
チェック内容はAWSの機密情報と、password=の文字列程度にしています。
* GitHubActionsの内容
* git secretsが失敗した時のログ https://github.com/BrainPad/cliboa/runs/3237622461?check_suite_focus=true
Confirmed
> [8/6〆]add git-secrets on security.yaml

- cliboa/cli/cliboadmin.py
Fixed a typo in the message displayed when a project is successfully created. (successfule to successful)
* Correctness of the modified word
Not necessary
This change has no effect on behavior.
> Fix message typo

- cliboa/scenario/extract/gcp.py
- cliboa/util/gcp.py
Issue: https://github.com/BrainPad/cliboa/issues/85
As to BigQueryWrite, it currently loads each _BULK_LINE_CNT rows into a table by using pandas-gbq, however, some issues occur in real use, such as:
Not supported functions by pandas-gbq
For instance, the time-partitioning setting is removed by overwriting a table.
Bulk update may hits the rate limit for updating a table by loading a big CSV file
pandas-gbq depends on slightly heavy libraries (pandas, numpy, etc.), which makes installing slow
I'm sure that it is better to use google-cloud-bigquery and to load a CSV file at once by bigquery.Client.load_table_from_file.
This change is destructive, but I believe in its effectiveness.
See also: https://cloud.google.com/bigquery/docs/pandas-gbq-migration
* 1 Check if Before Change Result and …
> Replace Panda with Big Query

- cliboa/scenario/__init__.py
- cliboa/scenario/load/gcp.py
- cliboa/scenario/transform/file.py
- cliboa/test/scenario/load/test_gcp.py
- cliboa/util/gcp.py
- docs/default_etl_modules.md
- docs/modules/bigquery_copy.md
A module to transfer query results of BigQuery table to an another Bigquery table
Issue: https://github.com/BrainPad/cliboa/issues/243
* 1 Behavior of BIgQueryCopy Module
* 2 Can copy a table to existing table
* 3 Can create and copy table if table not exist
Confirmed / Confirming / Not necessary
- Test bigquery client is called
- Test if Copy job is triggerd
> A module to transfer query results of BigQuery table to an another Bigquery table

- cliboa/scenario/extras.py
- cliboa/scenario/transform/csv.py
- cliboa/scenario/transform/file.py
複数ファイル処理中にエラーが発生した場合に継続するかエラーにするかを選べるようにしました。
親側だけで対応するのは難しく仕方なくサブクラス内で対応する方針としました。
> raise or skip

- cliboa/scenario/transform/csv.py
- docs/modules/csv_convert.md
Allow quote to be specified when reading csv using CsvConvert
Confirmed
* `As soon as possible`
> Allow quote to be specified when reading csv using CsvConvert

- .github/workflows/deploy.yaml
- setup.py
- tools/script/deploy_to_pypi.py
pypi にデプロイする時のshellコマンドを修正し、githubactionsのパッケージの作成とpypiへのアップロードのプロセスを分離しました。
pypiへのアップロードがうまくいかなかった原因としては、シェルによるpypiへのアップロードのプロセスが完了する前にpythonのプロセスが終わっていたためです。sleepを足すことでうまくいくようになりました。
pypi, test.pypi共にgithubflowから更新しました。バージョンは一つupしています。
https://test.pypi.org/project/cliboa/#history
https://pypi.org/project/cliboa/#history
タグとリリースノート
https://github.com/BrainPad/cliboa/releases/tag/v2.0.1beta
*  修正箇所
* pypiとtest.pypiのリリース履歴
* リリースノート
Confirming
> [11/19〆] fix pypi upload script

- cliboa/test/util/test_gpg.py
何故かGitHubActionsでGpgテストクラスが落ちていたので一時的にスキップしていたものを対応。
いろいろ検証したものの原因は不明ですが高確率で環境依存によるものです。
python3.7以上であればテストが通るので、とりあえずこれでプルリクを出します。
> Remove unittest.skip

- cliboa/scenario/transform/file.py
Add output log for targetfile to CsvConvert class
Not necessary
* `At the timing of your hand`
> Add output log for targetfile to CsvConvert class

- cliboa/template/Pipfile.above36
- cliboa/template/Pipfile.above37
- cliboa/template/Pipfile.above38
- cliboa/template/Pipfile.above39
- cliboa/template/requirements.above36.txt
- cliboa/template/requirements.above37.txt
- cliboa/template/requirements.above38.txt
- cliboa/template/requirements.above39.txt
Attempting to install psycopg2 in an environment without PostgreSQL fails with the following error.
```
pg_config is required to build psycopg2 from source.  Please add the directory
containing pg_config to the $PATH or specify the full executable path with the
option:
python setup.py build_ext --pg-config /path/to/pg_config build ...
or with the pg_config option in 'setup.cfg'.
If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.
For further information please check the 'doc/src/install.rst' file (also at
<https://www.psycopg.org/docs/install.html>).
```
Install psycopg2-binary instead of psycopg2.
Confirmed 
I confirmed that it behaved as …
> Use psycopg2-binary instead of psycopg2

- cliboa/scenario/extract/ftp.py
- cliboa/scenario/extract/sftp.py
- cliboa/scenario/ftp.py
- cliboa/scenario/sftp.py
- cliboa/scenario/transform/csv.py
- cliboa/scenario/transform/file.py
In the current source code, if the path specified when executing SftpUpload does not exist, the mkdir command will be executed and an error will occur.
In the first place, creating a path at the upload destination when executing SftpUpload is not the intended behavior.
The mkdir command can be executed only when SftpDownload is executed when the specified path does not exist.
Confirmed
I confirmed that it behaved as expected in the [Development-Environment](https://github.com/BrainPad/cliboa/wiki/Development-Environment) . 
* `I'd like to you to see it when you can see it.`
> Only SftpDownload can execute the mkdir command

- cliboa/template/Pipfile.above36
- cliboa/template/Pipfile.above37
- cliboa/template/Pipfile.above38
- cliboa/template/Pipfile.above39
- cliboa/template/requirements.above36.txt
- cliboa/template/requirements.above37.txt
- cliboa/template/requirements.above38.txt
- cliboa/template/requirements.above39.txt
- tools/docker/debian/Dockerfile
開発環境用DockerのDockerfileを更新しました。また、次の公式ドキュメントに記載の通りpsycopg2-binaryは本番用途に向かないようですので修正しました。
https://pypi.org/project/psycopg2/
issues
https://github.com/BrainPad/cliboa/issues/322
修正後のDockerfileでテストが処理されること。
補足
cliboaのpostgre機能を利用する場合、postgresql本体の関連ライブラリがインストールされる想定ですので、開発用dockerには必要最小限のライブラリのみ追加しました。
実行済み
お手隙の時に
> On branch 322 Update of debian Dockerfile for development

- setup.py
Remove Python 3.5 description from pypi
Not necessary
This change does not affect the actual processing.
* `I would like it at the timing of your chance.`
> Remove Python 3.5 description from pypi

- cliboa/scenario/transform/csv.py
- cliboa/scenario/transform/file.py
- cliboa/test/scenario/transform/test_file.py
To continue processing even if some files failed
This fix targets classes that do input / output for multiple files
Input is multiple files like CsvConcat, but it is one file at the time of output
Input is one file like File Divide, but output is not applicable to multiple files.
Confirmed
I confirmed that it behaved as expected in the [Development-Environment](https://github.com/BrainPad/cliboa/wiki/Development-Environment).
* `I'd like to you to see it when you can see it.`
> To continue processing even if some files failed

- cliboa/scenario/__init__.py
- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_column_delete.md
- docs/modules/csv_column_extract.md
Add CsvcolumnDelete
Restore the deletion mode of CsvColumnExtract performed by [This pull request](https://github.com/BrainPad/cliboa/pull/360) at the time of this correspondence to the state before implementation
* Is the deletion mode of CsvColumnExtract in the state before implementation?
* Validity of implementation contents of CsvcolumnDelete
Confirmed
> Add CsvcolumnDelete

- .github/workflows/security.yaml
git-secretsの修正
- gitのバージョンアップによりsayコマンドがなくなった（らしい）ので、sayコマンドのpathが通る様にした
- https://github.com/awslabs/git-secrets/issues/220
* CIが落ちていないか？
* この対応で問題ないか？
Confirmed
- CIが通った
- https://github.com/Tsuyoposon/cliboa/commit/22f7798fd4b5775ac7849ef5fa1b5cbdbae9a0db
* いつでも
> [modify] say command

- cliboa/scenario/transform/file.py
- cliboa/test/scenario/transform/test_file.py
- docs/modules/file_compress.md
FileCompress class must specify chunk_size as mandatory
Confirmed
> Set default value to chunk_size in FileCompress class

- cliboa/scenario/transform/file.py
- cliboa/test/scenario/transform/test_file.py
- docs/modules/file_divide.md
Allow changing suffix FileDivede Class
Confirmed
* `I hope you'll see it soon.`
> Allow changing suffix FileDivede Class

- cliboa/scenario/transform/file.py
- cliboa/test/scenario/transform/test_file.py
- docs/modules/file_rename.md
Add a mode to judge FileRename Class without distinguishing file extensions
Confirmed
> Add a mode to judge FileRename Class without distinguishing file extensions

- cliboa/adapter/sftp.py
- cliboa/scenario/load/sftp.py
- docs/modules/sftp_upload.md
Create a mode that does not generate intermediate files in SftpUpload.
Confirmed
I was able to transfer files using the modified SftpUpload class.  
I was able to transfer files by adding the put_intermediation option.  
I was able to transfer files by specifying None for the put_intermediation option.  
The contents of the file did not change before and after the transfer.  
I confirmed the above.  
> Create a mode that does not generate intermediate files in SftpUpload.

- cliboa/scenario/transform/csv.py
Make it start even if c parameter is not specified in CsvDuplicateRowDelete class.
* Is CsvDuplicateRowDelete class set to start even if dest_path is not specified?
Confirmed
* `I would appreciate it if you could check it when you have a chance.`
> Make it start even if dest_path parameter is not specified in CsvDuplicateRowDelete class.

- docs/json_configuration.md
- docs/yaml_configuration.md
Fixed invalid links in the documentation for YAML and JSON configuration files.
* Verify that document links have been correctly updated
* Confirm that the descriptions for YAML and JSON configuration files are appropriately updated
Not necessary
(Testing is not required as this is a documentation update only)
* None
> Fix invalid documentation links.

- README.md
The following corrections were made to the README file:
- Fixed typographical errors such as "Introction" to "Introduction" and "enviroment" to "environment".
- Clarified instructions and improved readability by rephrasing some sentences.
- Made adjustments to maintain consistency in formatting and terminology (e.g., ETL processing).
* Ensure all typographical errors have been corrected.
* Verify that the rephrased instructions maintain the original meaning and clarity.
* Check that all formatting is consistent with the rest of the document.
* Not necessary
(Testing is not required as this is a documentation update only)
* None
> Fix Typographical Errors in README

- cliboa/scenario/transform/csv.py
- cliboa/test/scenario/transform/test_csv.py
- docs/modules/csv_merge_exclusive.md
CsvMergeExclusive class delete rows when all column values match.
Confirmed
> CsvMergeExclusive class delete rows when all column values match.

- cliboa/scenario/__init__.py
- cliboa/scenario/load/aws.py
- cliboa/test/scenario/load/test_aws.py
- docs/default_etl_modules.md
- docs/modules/dynamodb_write.md
Add functionality to write data from CSV or JSONL files to DynamoDB tables
- Specify input file path, table name, and file format
- Support for CSV and JSONL input formats
This commit enables users to efficiently import data into DynamoDB tables from CSV or JSONL files.
This PR adds a new feature to write data from CSV or JSONL files to DynamoDB tables. Key features include:
User-specifiable parameters:
- Input file path
- Table name
- File format (CSV or JSONL)
Supported input formats:
- CSV
- JSONL
The implementation uses batch write operations to efficiently insert data into the DynamoDB table. This feature addition enables users to import datasets into DynamoDB tables from common file formats.
* Is the current approach to exception handling and logging consistent with other parts of …
> Implement DynamoDBWrite class.

- cliboa/adapter/http.py
- cliboa/core/validator.py
- cliboa/scenario/load/gcp.py
- cliboa/scenario/load/sftp.py
- cliboa/scenario/rdbms.py
- cliboa/scenario/transform/aes.py
- cliboa/scenario/transform/csv.py
- cliboa/scenario/transform/file.py
- cliboa/scenario/transform/gpg.py
- cliboa/scenario/transform/json.py
- cliboa/scenario/transform/system.py
- cliboa/test/adapter/test_http.py
The following corrections were made to resolve import-linter violations:
- Unified duplicate `EssentialParameters` classes by consolidating them in `scenario/validator.py` and removing from `core/validator.py`
- Updated all import statements across codebase to use the unified `EssentialParameters` from scenario layer
- Removed unused `FormAuth` class from `adapter/http.py` and its related tests as it was dead code
- Ensure all `EssentialParameters` imports now reference `scenario.validator` consistently
- Verify that `FormAuth` removal doesn't break any existing functionality (confirmed: only used in tests)
- Check that layered architecture violations are resolved (confirmed: import-linter now passes)
None
I've requested confirmation of the approach in #495 beforehand, but if this differs …
> fix: resolve import-linter violations and remove dead code

- docs/default_etl_modules.md
Updated default ETL modules documentation to accurately reflect available modules in codebase.
* Verify no modules with existing documentation files are missing from the list
* Verify GcsCopy module does not exist in codebase (removed from documentation)
Not necessary - Documentation-only changes
None
> docs: Update default ETL modules documentation

- cliboa/scenario/base.py
Fixes #541 
* Any unforeseen impact
* The overall quality is trending positively
Confirmed
Pass all CI.
> refactor: BaseStep support for multiple inheritance (Fixes #541)
